countries_dict = {
    'AFGHANISTAN': 'KABUL',
    'ALBANIA': 'TIRANA',
    'ALGERIA': 'ALGIERS',
    'ANDORRA': 'ANDORRA LA VELLA',
    'ANGOLA': 'LUANDA',
    'ARGENTINA': 'BUENOS AIRES',
    'ARMENIA': 'YEREVAN',
    'AUSTRALIA': '	CANBERRA',
    'AUSTRIA': 'VIENNA',
    'AZERBAIJAN': 'AZERBAIJAN',
}

